Add CI/CD workflows for Cloud Functions
mwvgroup/Pitt-Google-Broker pull request #190
Opened 2023-04-11 22:31 UTC by hernandezc1

2023-05-02 15:36 UTC, hernandezc1 commented on broker/cloud_functions/classify_snn/tests/test_cloud_fnc.py
This (fake) test case was purposely done in order for Daniel to show me that the test would successfully run

2023-05-04 16:55 UTC, Crash-GHaun commented
LGTM, although I'm not super familiar with GitHub Actions :)

2023-05-04 16:55 UTC, Crash-GHaun approved these changes

2023-07-31 14:10 UTC, djperrefort requested changes

2023-07-31 14:10 UTC, djperrefort commented on .github/workflows/TestCloudFunction.yml
> +  pull_request:
You don't need to include the `pull_request` option if you already have `push` enabled. 

There are cases where both are necessary. E.g.,when triggering on pushes/PRs on specific branches. However, this is not one of those cases.

2023-07-31 14:10 UTC, djperrefort commented on .github/workflows/TestCloudFunction.yml
> +    codacy-coverage-reporter:
`codacy-coverage-reporter` must be indented with two spaces, not four.

2023-08-10 13:07 UTC, djperrefort approved these changes

2023-08-10 21:28 UTC, merged