Update main/elasticc for schema version 0.9.1
mwvgroup/Pitt-Google-Broker pull request #197
Opened 2023-05-31 21:41 UTC by hernandezc1

Recently, ELAsTiCC began a test stream. As a result, they updated the schema version for the [alerts sent to brokers](https://github.com/LSSTDESC/elasticc/blob/main/alert_schema/elasticc.v0_9_1.alert.avsc) as well as the schema for [broker classifications](https://github.com/LSSTDESC/elasticc/blob/main/alert_schema/elasticc.v0_9_1.brokerClassification.avsc).

This PR serves to make any updates to the main/elasticc repo as a result of the new schemas

2023-06-07 18:02 UTC, hernandezc1 commented
When updating the `bq_elasticc_alerts_schema.json` file, I noticed that there are a few inconsistencies in the field names for the [schema version 0.9](https://github.com/LSSTDESC/plasticc_alerts/blob/main/Examples/plasticc_schema). For example, in the nested field `diaObject` there are some field names that are worded and/or spelled differently than what is written in the [elasticc.v0_9.diaObject.avsc file](https://github.com/LSSTDESC/plasticc_alerts/blob/main/Examples/plasticc_schema/elasticc.v0_9.diaObject.avsc)

In the elasticc.v0_9.diaObject.avsc file, we see the field name `hostgal_zspec`; In `bq_elasticc_alerts_schema.json`, it is written as `hostgal_z`
In the elasticc.v0_9.diaObject.avsc file, we see the field name `hostgal_zphot_q010`; In bq_elasticc_alerts_schema.json`, it is written as `hostgal_zphot_q10`
In the elasticc.v0_9.diaObject.avsc file, we see the field name `hostgal_zphot_q000`; This field does not exist in `bq_elasticc_alerts_schema.json`

Are these differences in naming convention important? I wanted to ask for your thoughts since the [schema version 0.9.1 ](https://github.com/LSSTDESC/elasticc/blob/main/alert_schema/elasticc.v0_9_1.diaObject.avsc)contains several of the same field names as the 0.9 version.

2023-06-21 08:16 UTC, troyraen requested changes
One required change:

In ps_to_gcs/main.py, line 20 needs to be changed to the following to accommodate the new broker-utils v0.2.47:

```
from broker_utils.avro_schemas.load import load_all_schemas
```

One question:

The PR makes changes to the BigQuery table schemas but the related module/resources are still commented out of the deployment script. I suppose that's ok since these changes don't break anything, but what's the plan there? Can we re-activate the cloud fnc as part of this PR or do you want to proceed without it? When I tried to test it I found two bugs: 1) an error in the topic name in the setup script; 2) main.py can't open the alert.

Two random things I noticed:

- the buckets are currently being created as multi-region; make them single region (`us-central1` is our default region)
- the setup script is creating a "reservoir" subscription to the alert_avros topic, but there's no need for it

Let's either change these here or create an issue to remind us to change in a future PR.

2023-06-21 08:23 UTC, troyraen commented
>  I suppose that's ok since these changes don't break anything

Actually, we can't tell whether these changes break something right now because we can't test them.

2023-08-16 19:04 UTC, hernandezc1 commented
@troyraen Hi Troy, I've gone ahead and tested some of the new changes in this PR. The `bq_elasticc_DIASource_schema.json` and `bq_elasticc_alerts_schema` can't be tested at the moment, but since any commands that use these files are commented out they will have to be tested in PR #196 

Please test these changes yourself when you get the chance; here is a link to the metrics for my re-deployment of the `upload_bytes_to_bucket` [Cloud Function](https://console.cloud.google.com/functions/details/us-central1/elasticc-upload_bytes_to_bucket-test?env=gen1&project=avid-heading-329016) as well as a link to the metrics to the `elastics-alert_avros` [Pub/Sub topic](https://console.cloud.google.com/cloudpubsub/topic/detail/elasticc-alert_avros?project=avid-heading-329016&tab=metrics). For easy access, here is the data & time range: Wednesday, August 16th; 2:46pm-3:10pm (EST)

2023-08-24 05:49 UTC, troyraen reviewed
There's a couple more things I noticed about resource locations. Otherwise looks good.

2023-08-24 05:49 UTC, troyraen commented on setup/setup_broker.sh
> +    gsutil mb -b on -l us-central1 "gs://${avro_bucket}"
- Make this region a variable so that it can be easily configured by the user of the script. 
- A related zone also needs to be passed into the create_vms.sh script in place of the environment variable it's currently using. 
- The bigquery dataset will also need to be created in the same location. 

It is important that all of these resources be created in the same region/zone for both speed and to avoid egress charges. If you want an example, look in the deploy branch. You can do these changes here or in a different PR if you want (just revert the changes above for this PR), but either way let's do them all in the same PR.

2023-08-24 21:04 UTC, troyraen approved these changes
LGTM

2023-08-25 01:22 UTC, merged